-- ============================================================================
-- Project AI Onboarding
-- Adds the fields required for the "Website -> AI analysis -> Review ->
-- Create Project -> Dashboard" onboarding flow.
--
-- Users only ever provide a website URL. Every other field is generated by
-- AI from that website:
--   - name              auto-derived from the domain (not AI, not user input)
--   - description       AI-generated, visible + editable
--   - keywords          AI-generated, visible + editable (existing column)
--   - intent_phrases    AI-generated, visible + editable (new)
--   - pain_phrases      AI-generated, visible + editable (new)
--   - competitors       AI-generated, visible + editable (new)
--   - hidden_keywords   AI-generated, NEVER shown to the user (new)
--   - subreddits        AI-generated, NEVER shown to the user (existing column,
--                        repurposed as the hidden subreddit set used later by
--                        the Reddit scanning engine)
--
-- Flat columns on `projects` are used for the MVP rather than a separate
-- profile table, per the confirmed architecture decision. RLS policies do
-- not need to change (they are row-level, not column-level); hiding
-- hidden_keywords/subreddits from end users is an application-layer
-- responsibility enforced by services/projects.ts, which never selects
-- those columns into a response that reaches a client component.
-- ============================================================================

alter table public.projects
  add column website_url text,
  add column hidden_keywords text[] not null default '{}',
  add column intent_phrases text[] not null default '{}',
  add column pain_phrases text[] not null default '{}',
  add column competitors text[] not null default '{}';

-- Backfill safety net in case any rows already exist without a website_url,
-- then enforce not-null going forward. No production data exists yet for
-- this feature, so this is a no-op in practice.
update public.projects set website_url = '' where website_url is null;

alter table public.projects
  alter column website_url set not null;

-- Business names are no longer user-provided, so uniqueness is now enforced
-- on the website instead of the (previously user-typed) name.
alter table public.projects
  drop constraint projects_user_name_unique;

alter table public.projects
  add constraint projects_user_website_url_unique unique (user_id, website_url);

comment on column public.projects.website_url is 'The website URL the user submitted. Sole input to the AI onboarding flow.';
comment on column public.projects.name is 'Auto-derived from the website domain; users do not set this directly.';
comment on column public.projects.description is 'AI-generated business description. Visible and editable by the user.';
comment on column public.projects.keywords is 'AI-generated keywords. Visible and editable by the user.';
comment on column public.projects.intent_phrases is 'AI-generated intent phrases (buying/searching signals). Visible and editable by the user.';
comment on column public.projects.pain_phrases is 'AI-generated pain phrases (frustration/complaint signals). Visible and editable by the user.';
comment on column public.projects.competitors is 'AI-generated competitor names. Visible and editable by the user.';
comment on column public.projects.hidden_keywords is 'AI-generated hidden keyword variations used for lead matching. Never exposed to the client.';
comment on column public.projects.subreddits is 'AI-generated hidden subreddits used later by the Reddit scanning engine. Never exposed to the client.';
comment on constraint projects_user_website_url_unique on public.projects is 'Prevents a user from creating two projects for the same website.';
